"""enhance_mcp_hub_skills_sops

Revision ID: 10703a671de6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-03 18:28:28.845727

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '10703a671de6'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_sessions', sa.Column('identity_binding', sa.JSON(), nullable=True))
    op.add_column('mcp_sessions', sa.Column('credential_config', sa.JSON(), nullable=True))
    op.add_column('skills', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('sop_steps', sa.Column('target_agent_type_id', sa.UUID(), nullable=True))
    op.add_column('sop_steps', sa.Column('step_config', sa.JSON(), nullable=True))
    op.drop_column('sop_steps', 'delegate_agent_type_id')
    op.add_column('sops', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Rename SopStepType enum value: 'skill' -> 'skill_invocation'
    # Cast to VARCHAR first (removes enum dependency), update data, recreate enum cleanly.
    # Note: ADD VALUE + UPDATE in the same transaction is unsafe in PostgreSQL, so we
    # skip ADD VALUE and go directly through VARCHAR as intermediate type.
    op.execute("ALTER TABLE sop_steps ALTER COLUMN step_type TYPE VARCHAR(50)")
    op.execute("DROP TYPE sop_step_type_enum")
    op.execute("UPDATE sop_steps SET step_type = 'skill_invocation' WHERE step_type = 'skill'")
    op.execute("CREATE TYPE sop_step_type_enum AS ENUM ('skill_invocation', 'agent_delegation')")
    op.execute(
        "ALTER TABLE sop_steps ALTER COLUMN step_type TYPE sop_step_type_enum "
        "USING step_type::sop_step_type_enum"
    )


def downgrade() -> None:
    # Revert SopStepType enum value: 'skill_invocation' -> 'skill'
    op.execute("ALTER TABLE sop_steps ALTER COLUMN step_type TYPE VARCHAR(50)")
    op.execute("DROP TYPE sop_step_type_enum")
    op.execute("CREATE TYPE sop_step_type_enum AS ENUM ('skill', 'agent_delegation')")
    op.execute("UPDATE sop_steps SET step_type = 'skill' WHERE step_type = 'skill_invocation'")
    op.execute(
        "ALTER TABLE sop_steps ALTER COLUMN step_type TYPE sop_step_type_enum "
        "USING step_type::sop_step_type_enum"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sops', 'instructions')
    op.add_column('sop_steps', sa.Column('delegate_agent_type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('sop_steps', 'step_config')
    op.drop_column('sop_steps', 'target_agent_type_id')
    op.drop_column('skills', 'instructions')
    op.drop_column('mcp_sessions', 'credential_config')
    op.drop_column('mcp_sessions', 'identity_binding')
    # ### end Alembic commands ###
