"""add-model-config-agent-type-model-config-id-conversation-history

Revision ID: 232324b61ea4
Revises: d34d6078aae3
Create Date: 2026-05-05 23:08:38.516517

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232324b61ea4'
down_revision: str | None = 'd34d6078aae3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.Enum('openai', 'anthropic', 'litellm_proxy', 'azure_openai', name='model_provider_enum'), nullable=False),
    sa.Column('api_base_url', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.add_column('agent_jobs', sa.Column('conversation_history', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # Note: uq_agent_role_skill and uq_agent_role_sop already exist in DB (applied via earlier migration)
    op.add_column('agent_types', sa.Column('model_config_id', sa.UUID(), nullable=True))
    op.add_column('agent_types', sa.Column('model_name', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'agent_types', 'model_configs', ['model_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agent_types', 'llm_provider')
    op.drop_column('agent_types', 'llm_model')
    op.drop_column('agent_types', 'encrypted_llm_credentials')
    op.add_column('mcp_sessions', sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_sessions', 'oauth_metadata')
    op.drop_column('mcp_sessions', 'oauth_refresh_expires_at')
    op.drop_column('mcp_sessions', 'oauth_expires_at')
    op.add_column('agent_types', sa.Column('encrypted_llm_credentials', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_types', sa.Column('llm_model', sa.VARCHAR(length=200), autoincrement=False, nullable=False, server_default='gpt-4o'))
    op.add_column('agent_types', sa.Column('llm_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default='openai'))
    op.drop_constraint(None, 'agent_types', type_='foreignkey')
    op.drop_column('agent_types', 'model_name')
    op.drop_column('agent_types', 'model_config_id')
    # Note: uq_agent_role_skill and uq_agent_role_sop are NOT dropped (they pre-existed)
    op.drop_column('agent_jobs', 'conversation_history')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
