"""agent_runtime_security_segregation

Revision ID: 385c4ae051f6
Revises: 6f9408e281d7
Create Date: 2026-05-13 16:33:09.377844

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385c4ae051f6'
down_revision: str | None = '6f9408e281d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all enum types explicitly (idempotent via Python-level existence check)
    bind = op.get_bind()
    existing_enums = {row[0] for row in bind.execute(sa.text(
        "SELECT typname FROM pg_type WHERE typname IN ("
        "'cert_validation_outcome_enum', 'token_refresh_outcome_enum', "
        "'agent_certificate_status_enum', 'agent_token_status_enum')"
    ))}
    if 'cert_validation_outcome_enum' not in existing_enums:
        op.execute(sa.text("CREATE TYPE cert_validation_outcome_enum AS ENUM ('valid', 'expired', 'revoked', 'invalid_signature')"))
    if 'token_refresh_outcome_enum' not in existing_enums:
        op.execute(sa.text("CREATE TYPE token_refresh_outcome_enum AS ENUM ('success', 'failure', 'rate_limited')"))
    if 'agent_certificate_status_enum' not in existing_enums:
        op.execute(sa.text("CREATE TYPE agent_certificate_status_enum AS ENUM ('active', 'expired', 'revoked')"))
    if 'agent_token_status_enum' not in existing_enums:
        op.execute(sa.text("CREATE TYPE agent_token_status_enum AS ENUM ('active', 'expired', 'refresh_failed')"))
    op.create_table('certificate_revocation_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', name='uq_crl_serial_number')
    )
    op.create_table('certificate_validation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_serial_number', sa.String(length=200), nullable=False),
    sa.Column('certificate_cn', sa.String(length=500), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', postgresql.ENUM('valid', 'expired', 'revoked', 'invalid_signature', name='cert_validation_outcome_enum', create_type=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('validated_by_service', sa.String(length=200), nullable=False),
    sa.Column('requested_operation', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cert_validation_logs_serial_number', 'certificate_validation_logs', ['certificate_serial_number'], unique=False)
    op.create_index('ix_cert_validation_logs_validated_at', 'certificate_validation_logs', ['validated_at'], unique=False)
    op.create_table('token_refresh_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_identity_id', sa.UUID(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', postgresql.ENUM('success', 'failure', 'rate_limited', name='token_refresh_outcome_enum', create_type=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_identity_id'], ['agent_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_refresh_logs_agent_identity_id', 'token_refresh_logs', ['agent_identity_id'], unique=False)
    op.create_index('ix_token_refresh_logs_attempted_at', 'token_refresh_logs', ['attempted_at'], unique=False)
    op.create_table('agent_instance_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.String(length=500), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'expired', 'revoked', name='agent_certificate_status_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_instance_certs_agent_type_id', 'agent_instance_certificates', ['agent_type_id'], unique=False)
    op.create_index('ix_agent_instance_certs_serial_number', 'agent_instance_certificates', ['serial_number'], unique=False)
    op.add_column('agent_identities', sa.Column('encrypted_refresh_token', sa.Text(), nullable=True))
    op.add_column('agent_identities', sa.Column('last_token_refresh_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_identities', sa.Column('token_status', postgresql.ENUM('active', 'expired', 'refresh_failed', name='agent_token_status_enum', create_type=False), nullable=True))
    # Data migration - copy existing refresh_token to encrypted_refresh_token
    op.execute("""
        UPDATE agent_identities
        SET encrypted_refresh_token = refresh_token,
            token_status = 'active'
        WHERE refresh_token IS NOT NULL
          AND encrypted_refresh_token IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_identities', 'token_status')
    op.drop_column('agent_identities', 'last_token_refresh_at')
    op.drop_column('agent_identities', 'encrypted_refresh_token')
    op.drop_index('ix_agent_instance_certs_serial_number', table_name='agent_instance_certificates')
    op.drop_index('ix_agent_instance_certs_agent_type_id', table_name='agent_instance_certificates')
    op.drop_table('agent_instance_certificates')
    op.drop_index('ix_token_refresh_logs_attempted_at', table_name='token_refresh_logs')
    op.drop_index('ix_token_refresh_logs_agent_identity_id', table_name='token_refresh_logs')
    op.drop_table('token_refresh_logs')
    op.drop_index('ix_cert_validation_logs_validated_at', table_name='certificate_validation_logs')
    op.drop_index('ix_cert_validation_logs_serial_number', table_name='certificate_validation_logs')
    op.drop_table('certificate_validation_logs')
    op.drop_table('certificate_revocation_entries')
    # Drop all enum types created in upgrade
    op.execute("DROP TYPE IF EXISTS agent_token_status_enum")
    op.execute("DROP TYPE IF EXISTS agent_certificate_status_enum")
    op.execute("DROP TYPE IF EXISTS token_refresh_outcome_enum")
    op.execute("DROP TYPE IF EXISTS cert_validation_outcome_enum")
    # ### end Alembic commands ###

