"""refine_oidc_integration

Revision ID: 49ab45b8226e
Revises: 868d278f04db
Create Date: 2026-07-07 14:54:56.478469

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ab45b8226e'
down_revision: str | None = '868d278f04db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False, comment='Immutable super admin username; sourced from SUPER_ADMIN_USERNAME env var'),
    sa.Column('hashed_password', sa.String(length=500), nullable=False, comment='Argon2id or bcrypt hash of the super admin password'),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent super admin authentication'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('identity_provider_config_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.String(length=500), nullable=False, comment='Identity of the admin who made the change (super admin username or OIDC subject)'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='created | updated | tested | deleted'),
    sa.Column('changed_fields', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Array of field names that were modified'),
    sa.Column('previous_values', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Snapshot of config values before the change, for rollback reference'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['identity_provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Add new columns as nullable first to allow backfill
    op.add_column('identity_provider_configs', sa.Column('provider_scope', sa.String(length=50), nullable=True, comment='user | agent'))
    op.add_column('identity_provider_configs', sa.Column('display_name', sa.String(length=500), nullable=True))
    op.add_column('identity_provider_configs', sa.Column('issuer_url', sa.String(length=2048), nullable=True))
    op.add_column('identity_provider_configs', sa.Column('encrypted_client_secret', sa.String(length=2048), nullable=True, comment='AES-256-GCM encrypted client secret'))
    op.add_column('identity_provider_configs', sa.Column('scopes', sa.String(length=500), nullable=True))
    op.add_column('identity_provider_configs', sa.Column('claim_mappings', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="OIDC claim to platform field mappings (e.g. {'sub': 'subject'})"))
    op.add_column('identity_provider_configs', sa.Column('is_enabled', sa.Boolean(), nullable=True))

    # Backfill existing rows from old columns
    op.execute("UPDATE identity_provider_configs SET issuer_url = oidc_provider_url WHERE issuer_url IS NULL AND oidc_provider_url IS NOT NULL")
    op.execute("UPDATE identity_provider_configs SET encrypted_client_secret = client_secret WHERE encrypted_client_secret IS NULL AND client_secret IS NOT NULL")
    op.execute("UPDATE identity_provider_configs SET provider_scope = 'user' WHERE provider_scope IS NULL")
    op.execute("UPDATE identity_provider_configs SET display_name = COALESCE(NULLIF(TRIM(provider_type || ' Provider'), ''), 'Identity Provider') WHERE display_name IS NULL")
    op.execute("UPDATE identity_provider_configs SET scopes = 'openid profile email' WHERE scopes IS NULL")
    op.execute("UPDATE identity_provider_configs SET is_enabled = true WHERE is_enabled IS NULL")

    # Now set NOT NULL constraints
    op.alter_column('identity_provider_configs', 'provider_scope', existing_type=sa.String(length=50), nullable=False)
    op.alter_column('identity_provider_configs', 'display_name', existing_type=sa.String(length=500), nullable=False)
    op.alter_column('identity_provider_configs', 'issuer_url', existing_type=sa.String(length=2048), nullable=False)
    op.alter_column('identity_provider_configs', 'scopes', existing_type=sa.String(length=500), nullable=False, server_default=sa.text("'openid profile email'"))
    op.alter_column('identity_provider_configs', 'is_enabled', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('true'))

    op.alter_column('identity_provider_configs', 'provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment='oidc_generic | keycloak | azure_entraid',
               existing_comment='keycloak_bundled | keycloak_external | azure_entraid',
               existing_nullable=False)
    op.drop_constraint(op.f('identity_provider_configs_setup_completed_by_id_fkey'), 'identity_provider_configs', type_='foreignkey')
    op.drop_column('identity_provider_configs', 'audience')
    op.drop_column('identity_provider_configs', 'is_setup_complete')
    op.drop_column('identity_provider_configs', 'realm_name')
    op.drop_column('identity_provider_configs', 'client_secret')
    op.drop_column('identity_provider_configs', 'setup_completed_at')
    op.drop_column('identity_provider_configs', 'setup_completed_by_id')
    op.drop_column('identity_provider_configs', 'oidc_provider_url')
    op.add_column('identity_provider_setup_state', sa.Column('user_provider_configured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('identity_provider_setup_state', sa.Column('agent_provider_configured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_provider_setup_state', 'agent_provider_configured')
    op.drop_column('identity_provider_setup_state', 'user_provider_configured')
    op.add_column('identity_provider_configs', sa.Column('oidc_provider_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.add_column('identity_provider_configs', sa.Column('setup_completed_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('identity_provider_configs', sa.Column('setup_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('identity_provider_configs', sa.Column('client_secret', sa.VARCHAR(length=2048), autoincrement=False, nullable=True, comment='AES-256-GCM encrypted client secret'))
    op.add_column('identity_provider_configs', sa.Column('realm_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('identity_provider_configs', sa.Column('is_setup_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('identity_provider_configs', sa.Column('audience', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('identity_provider_configs_setup_completed_by_id_fkey'), 'identity_provider_configs', 'identities', ['setup_completed_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('identity_provider_configs', 'provider_type',
               existing_type=sa.VARCHAR(length=50),
               comment='keycloak_bundled | keycloak_external | azure_entraid',
               existing_comment='oidc_generic | keycloak | azure_entraid',
               existing_nullable=False)
    op.drop_column('identity_provider_configs', 'is_enabled')
    op.drop_column('identity_provider_configs', 'claim_mappings')
    op.drop_column('identity_provider_configs', 'scopes')
    op.drop_column('identity_provider_configs', 'encrypted_client_secret')
    op.drop_column('identity_provider_configs', 'issuer_url')
    op.drop_column('identity_provider_configs', 'display_name')
    op.drop_column('identity_provider_configs', 'provider_scope')
    op.drop_table('identity_provider_config_audits')
    op.drop_table('super_admin_credentials')
    # ### end Alembic commands ###
