"""implement_notification_system

Revision ID: 4cd1efec6451
Revises: 385c4ae051f6
Create Date: 2026-05-14 09:46:43.552501

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd1efec6451'
down_revision: str | None = '385c4ae051f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Migrate channel_type_enum: old values (email, slack, teams, webhook) -> new values (SMTP, EMAIL_API, WEBHOOK, MESSENGER)
    op.execute("ALTER TYPE channel_type_enum RENAME TO channel_type_enum_old")
    op.execute("CREATE TYPE channel_type_enum AS ENUM ('SMTP', 'EMAIL_API', 'WEBHOOK', 'MESSENGER')")
    op.execute(
        "ALTER TABLE notification_channels ALTER COLUMN channel_type TYPE channel_type_enum "
        "USING CASE channel_type::text "
        "  WHEN 'email' THEN 'SMTP'::channel_type_enum "
        "  WHEN 'slack' THEN 'MESSENGER'::channel_type_enum "
        "  WHEN 'teams' THEN 'MESSENGER'::channel_type_enum "
        "  WHEN 'webhook' THEN 'WEBHOOK'::channel_type_enum "
        "  ELSE 'WEBHOOK'::channel_type_enum "
        "END"
    )
    op.execute("DROP TYPE channel_type_enum_old")

    op.create_table('recipient_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_recipient_groups_slug'), 'recipient_groups', ['slug'], unique=True)
    op.create_table('channel_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'key', name='uq_channel_property_key')
    )
    op.create_index(op.f('ix_channel_properties_channel_id'), 'channel_properties', ['channel_id'], unique=False)
    op.create_table('group_channel_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['recipient_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'channel_id', name='uq_group_channel')
    )
    op.create_index(op.f('ix_group_channel_mappings_channel_id'), 'group_channel_mappings', ['channel_id'], unique=False)
    op.create_index(op.f('ix_group_channel_mappings_group_id'), 'group_channel_mappings', ['group_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('SOP', 'AGENT', 'MANUAL', name='source_type_enum'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=500), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'delivered', 'failed', name='delivery_status_enum', create_type=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['recipient_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_channel_id'), 'notification_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_group_id'), 'notification_logs', ['group_id'], unique=False)
    op.drop_column('notification_channels', 'encrypted_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_channels', sa.Column('encrypted_config', sa.TEXT(), autoincrement=False, nullable=True))

    # Revert channel_type_enum to old values
    op.execute("ALTER TYPE channel_type_enum RENAME TO channel_type_enum_new")
    op.execute("CREATE TYPE channel_type_enum AS ENUM ('email', 'slack', 'teams', 'webhook')")
    op.execute(
        "ALTER TABLE notification_channels ALTER COLUMN channel_type TYPE channel_type_enum "
        "USING CASE channel_type::text "
        "  WHEN 'SMTP' THEN 'email'::channel_type_enum "
        "  WHEN 'EMAIL_API' THEN 'email'::channel_type_enum "
        "  WHEN 'WEBHOOK' THEN 'webhook'::channel_type_enum "
        "  WHEN 'MESSENGER' THEN 'slack'::channel_type_enum "
        "  ELSE 'webhook'::channel_type_enum "
        "END"
    )
    op.execute("DROP TYPE channel_type_enum_new")
    op.drop_index(op.f('ix_notification_logs_group_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_group_channel_mappings_group_id'), table_name='group_channel_mappings')
    op.drop_index(op.f('ix_group_channel_mappings_channel_id'), table_name='group_channel_mappings')
    op.drop_table('group_channel_mappings')
    op.drop_index(op.f('ix_channel_properties_channel_id'), table_name='channel_properties')
    op.drop_table('channel_properties')
    op.drop_index(op.f('ix_recipient_groups_slug'), table_name='recipient_groups')
    op.drop_table('recipient_groups')
    # ### end Alembic commands ###
