"""add_is_system_to_roles

Revision ID: 52908f217517
Revises: d736a85c26fd
Create Date: 2026-04-26 18:20:05.803355

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '52908f217517'
down_revision: str | None = 'd736a85c26fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system')
    # ### end Alembic commands ###
