"""add_allowed_identity_types_to_agent_role

Revision ID: 53f351b9acd8
Revises: 929e90ddcc2c
Create Date: 2026-05-07 21:27:33.440678

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f351b9acd8'
down_revision: str | None = '929e90ddcc2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraints already exist, skip creation
    # op.create_unique_constraint('uq_agent_role_skill', 'agent_role_skills', ['role_id', 'skill_id'])
    # op.create_unique_constraint('uq_agent_role_sop', 'agent_role_sops', ['role_id', 'sop_id'])
    op.add_column('agent_roles', sa.Column(
        'allowed_identity_types',
        postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        server_default='[]',
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_roles', 'allowed_identity_types')
    # Constraints were not created by this migration, skip drop
    # op.drop_constraint('uq_agent_role_sop', 'agent_role_sops', type_='unique')
    # op.drop_constraint('uq_agent_role_skill', 'agent_role_skills', type_='unique')
    # ### end Alembic commands ###
