"""promote_conversation_session

Revision ID: 6f9408e281d7
Revises: 5c2910c238a8
Create Date: 2026-05-13 09:35:26.692034

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6f9408e281d7'
down_revision: str | None = '5c2910c238a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add new enum value to conversation_status_enum (must be done before column operations)
    op.execute("ALTER TYPE conversation_status_enum ADD VALUE IF NOT EXISTS 'archived'")
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unrelated agent_role_* constraint changes that already exist in database
    op.add_column('conversation_sessions', sa.Column('triggered_by_user_id', sa.UUID(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('agent_job_id', sa.UUID(), nullable=True))
    op.add_column('conversation_sessions', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('conversation_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('conversation_sessions_agent_instance_id_fkey'), 'conversation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_sessions', 'agent_jobs', ['agent_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation_sessions', 'identities', ['triggered_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversation_sessions', 'agent_types', ['agent_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('conversation_sessions', 'initiator_subject')
    op.drop_column('conversation_sessions', 'agent_instance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_sessions', sa.Column('agent_instance_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('conversation_sessions', sa.Column('initiator_subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'conversation_sessions', type_='foreignkey')
    op.drop_constraint(None, 'conversation_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_sessions_agent_instance_id_fkey'), 'conversation_sessions', 'agent_instances', ['agent_instance_id'], ['id'], ondelete='SET NULL')
    op.drop_column('conversation_sessions', 'updated_at')
    op.drop_column('conversation_sessions', 'title')
    op.drop_column('conversation_sessions', 'agent_job_id')
    op.drop_column('conversation_sessions', 'triggered_by_user_id')
    op.drop_constraint('uq_agent_role_sop', 'agent_role_sops', type_='unique')
    op.drop_constraint('uq_agent_role_skill', 'agent_role_skills', type_='unique')
    op.drop_constraint('uq_agent_role_identity', 'agent_role_identities', type_='unique')
    op.create_index(op.f('ix_agent_role_identities_role_id'), 'agent_role_identities', ['role_id'], unique=False)
    # Removed unrelated agent_role_* constraint changes