"""replace_allowed_identity_types_with_agent_role_identities

Revision ID: 7a9f2e3b4c5d
Revises: 53f351b9acd8
Create Date: 2026-05-08 10:30:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a9f2e3b4c5d'
down_revision: Union[str, None] = '53f351b9acd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create agent_role_identities join table
    op.create_table(
        'agent_role_identities',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('identity_id', sa.UUID(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('assigned_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['identity_id'], ['agent_identities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['agent_roles.id'], ondelete='CASCADE'),
        # Note: assigned_by FK to users table omitted as users table may not exist yet
        sa.PrimaryKeyConstraint('role_id', 'identity_id'),
        sa.UniqueConstraint('role_id', 'identity_id', name='uq_agent_role_identity')
    )
    op.create_index(op.f('ix_agent_role_identities_identity_id'), 'agent_role_identities', ['identity_id'], unique=False)
    op.create_index(op.f('ix_agent_role_identities_role_id'), 'agent_role_identities', ['role_id'], unique=False)
    
    # Drop allowed_identity_types column from agent_roles
    op.drop_column('agent_roles', 'allowed_identity_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add allowed_identity_types column
    op.add_column('agent_roles', sa.Column(
        'allowed_identity_types',
        postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        server_default='[]',
    ))
    
    # Drop agent_role_identities table
    op.drop_index(op.f('ix_agent_role_identities_role_id'), table_name='agent_role_identities')
    op.drop_index(op.f('ix_agent_role_identities_identity_id'), table_name='agent_role_identities')
    op.drop_table('agent_role_identities')
    # ### end Alembic commands ###
