"""add_agent_a2a_sessions_table

Revision ID: 84c67e8c28d8
Revises: aac57a284ad2
Create Date: 2026-05-20 22:12:48.425017

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c67e8c28d8'
down_revision: str | None = 'aac57a284ad2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_unique_constraint_if_missing(
    table_name: str,
    constraint_name: str,
    columns: list[str],
) -> None:
    """Create a unique constraint only when it does not already exist."""
    bind = op.get_bind()
    exists = bind.execute(
        sa.text(
            """
            SELECT 1
            FROM pg_constraint
            WHERE conname = :constraint_name
            UNION ALL
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = :constraint_name
              AND n.nspname = current_schema()
            LIMIT 1
            """
        ),
        {"constraint_name": constraint_name},
    ).scalar()
    if not exists:
        op.create_unique_constraint(constraint_name, table_name, columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_a2a_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_instance_id', sa.String(length=200), nullable=False),
    sa.Column('receiver_instance_id', sa.String(length=200), nullable=False),
    sa.Column('receiver_is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('session_link_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', name='a2a_session_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disconnect_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_link_id')
    )
    op.create_index('ix_agent_a2a_sessions_receiver', 'agent_a2a_sessions', ['receiver_instance_id'], unique=False)
    op.create_index('ix_agent_a2a_sessions_requester', 'agent_a2a_sessions', ['requester_instance_id'], unique=False)
    op.drop_table('gateway_routes')
    op.drop_index(op.f('ix_agent_role_identities_identity_id'), table_name='agent_role_identities')
    op.drop_index(op.f('ix_agent_role_identities_role_id'), table_name='agent_role_identities')
    _create_unique_constraint_if_missing('agent_role_identities', 'uq_agent_role_identity', ['role_id', 'identity_id'])
    _create_unique_constraint_if_missing('agent_role_skills', 'uq_agent_role_skill', ['role_id', 'skill_id'])
    _create_unique_constraint_if_missing('agent_role_sops', 'uq_agent_role_sop', ['role_id', 'sop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agent_role_sop', 'agent_role_sops', type_='unique')
    op.drop_constraint('uq_agent_role_skill', 'agent_role_skills', type_='unique')
    op.drop_constraint('uq_agent_role_identity', 'agent_role_identities', type_='unique')
    op.create_index(op.f('ix_agent_role_identities_role_id'), 'agent_role_identities', ['role_id'], unique=False)
    op.create_index(op.f('ix_agent_role_identities_identity_id'), 'agent_role_identities', ['identity_id'], unique=False)
    op.create_table('gateway_routes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('http_base_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gateway_routes_pkey')),
    sa.UniqueConstraint('agent_type_id', name=op.f('gateway_routes_agent_type_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_agent_a2a_sessions_requester', table_name='agent_a2a_sessions')
    op.drop_index('ix_agent_a2a_sessions_receiver', table_name='agent_a2a_sessions')
    op.drop_table('agent_a2a_sessions')
    # ### end Alembic commands ###
