"""add-execution-logs-prompt-capture-table

Revision ID: 8612fc7e10a7
Revises: 226f86ce62ae
Create Date: 2026-05-06 21:13:55.603996

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8612fc7e10a7'
down_revision: str | None = '226f86ce62ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('system_instruction', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_logs_session_id', 'execution_logs', ['session_id'], unique=False)
    # Note: uq_agent_role_skill and uq_agent_role_sop already exist in DB (applied via earlier migration)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_logs_session_id', table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###
