"""add_primary_sop_id_only

Revision ID: 929e90ddcc2c
Revises: 8612fc7e10a7
Create Date: 2026-05-07 12:23:55.603737

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '929e90ddcc2c'
down_revision: str | None = '8612fc7e10a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_types', sa.Column('primary_sop_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agent_types', 'sops', ['primary_sop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_types', type_='foreignkey')
    op.drop_column('agent_types', 'primary_sop_id')
    # ### end Alembic commands ###
