"""add_agent_data_table

Revision ID: 9d7152156e11
Revises: a1d4e8f2b3c5
Create Date: 2026-07-03 13:49:50.331708

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d7152156e11'
down_revision: str | None = 'a1d4e8f2b3c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('data_name', sa.String(length=255), nullable=False),
    sa.Column('data_value', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_data_agent_type_id_data_name', 'agent_data', ['agent_type_id', 'data_name'], unique=False)
    op.create_index(op.f('ix_agent_data_data_name'), 'agent_data', ['data_name'], unique=False)
    op.create_index('ix_agent_data_session_id_data_name', 'agent_data', ['session_id', 'data_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_data_session_id_data_name', table_name='agent_data')
    op.drop_index(op.f('ix_agent_data_data_name'), table_name='agent_data')
    op.drop_index('ix_agent_data_agent_type_id_data_name', table_name='agent_data')
    op.drop_table('agent_data')
    # ### end Alembic commands ###
