"""add agent execution guardrail policy and stop metadata

Revision ID: a44d298ae1f5
Revises: 84c67e8c28d8
Create Date: 2026-05-24 14:40:45.633536

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a44d298ae1f5'
down_revision: str | None = '84c67e8c28d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE agent_job_stop_category_enum AS ENUM ('functional_failure', 'guardrail_stop')")
    op.execute(
        "CREATE TYPE agent_job_stop_reason_enum AS ENUM ("
        "'cycle_detected', 'iteration_limit_exceeded', 'delegation_depth_exceeded', "
        "'delegated_steps_exceeded', 'execution_timeout_exceeded', "
        "'token_budget_exceeded_non_conversational', 'token_guardrail_fallback_applied'"
        ")"
    )
    op.execute("CREATE TYPE guardrail_token_enforcement_mode_enum AS ENUM ('observe', 'enforce')")
    op.execute(
        "CREATE TYPE guardrail_token_fallback_mode_enum AS ENUM ("
        "'observe_and_log', 'stop_on_next_hard_guardrail'"
        ")"
    )
    op.execute(
        "CREATE TYPE guardrail_conversational_token_visibility_mode_enum AS ENUM ('enabled', 'disabled')"
    )
    op.execute(
        "CREATE TYPE guardrail_conversational_continuation_policy_enum AS ENUM ('allow')"
    )
    op.add_column('agent_jobs', sa.Column('stop_category', postgresql.ENUM('functional_failure', 'guardrail_stop', name='agent_job_stop_category_enum', create_type=False), nullable=True))
    op.add_column('agent_jobs', sa.Column('stop_reason', postgresql.ENUM('cycle_detected', 'iteration_limit_exceeded', 'delegation_depth_exceeded', 'delegated_steps_exceeded', 'execution_timeout_exceeded', 'token_budget_exceeded_non_conversational', 'token_guardrail_fallback_applied', name='agent_job_stop_reason_enum', create_type=False), nullable=True))
    op.add_column('agent_jobs', sa.Column('stop_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_types', sa.Column('guardrail_max_iterations', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('agent_types', sa.Column('guardrail_max_delegation_depth', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('agent_types', sa.Column('guardrail_max_delegated_steps', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('agent_types', sa.Column('guardrail_execution_timeout_seconds', sa.Integer(), nullable=False, server_default='300'))
    op.add_column('agent_types', sa.Column('guardrail_token_budget', sa.Integer(), nullable=True))
    op.add_column('agent_types', sa.Column('guardrail_token_enforcement_mode', postgresql.ENUM('observe', 'enforce', name='guardrail_token_enforcement_mode_enum', create_type=False), nullable=False, server_default='observe'))
    op.add_column('agent_types', sa.Column('guardrail_token_fallback_mode', postgresql.ENUM('observe_and_log', 'stop_on_next_hard_guardrail', name='guardrail_token_fallback_mode_enum', create_type=False), nullable=False, server_default='observe_and_log'))
    op.add_column('agent_types', sa.Column('guardrail_conversational_token_visibility_mode', postgresql.ENUM('enabled', 'disabled', name='guardrail_conversational_token_visibility_mode_enum', create_type=False), nullable=False, server_default='enabled'))
    op.add_column('agent_types', sa.Column('guardrail_conversational_continuation_policy', postgresql.ENUM('allow', name='guardrail_conversational_continuation_policy_enum', create_type=False), nullable=False, server_default='allow'))
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_max_iterations DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_max_delegation_depth DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_max_delegated_steps DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_execution_timeout_seconds DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_token_enforcement_mode DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_token_fallback_mode DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_conversational_token_visibility_mode DROP DEFAULT")
    op.execute("ALTER TABLE agent_types ALTER COLUMN guardrail_conversational_continuation_policy DROP DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_types', 'guardrail_conversational_continuation_policy')
    op.drop_column('agent_types', 'guardrail_conversational_token_visibility_mode')
    op.drop_column('agent_types', 'guardrail_token_fallback_mode')
    op.drop_column('agent_types', 'guardrail_token_enforcement_mode')
    op.drop_column('agent_types', 'guardrail_token_budget')
    op.drop_column('agent_types', 'guardrail_execution_timeout_seconds')
    op.drop_column('agent_types', 'guardrail_max_delegated_steps')
    op.drop_column('agent_types', 'guardrail_max_delegation_depth')
    op.drop_column('agent_types', 'guardrail_max_iterations')
    op.drop_column('agent_jobs', 'stop_details')
    op.drop_column('agent_jobs', 'stop_reason')
    op.drop_column('agent_jobs', 'stop_category')
    op.execute('DROP TYPE IF EXISTS guardrail_conversational_continuation_policy_enum')
    op.execute('DROP TYPE IF EXISTS guardrail_conversational_token_visibility_mode_enum')
    op.execute('DROP TYPE IF EXISTS guardrail_token_fallback_mode_enum')
    op.execute('DROP TYPE IF EXISTS guardrail_token_enforcement_mode_enum')
    op.execute('DROP TYPE IF EXISTS agent_job_stop_reason_enum')
    op.execute('DROP TYPE IF EXISTS agent_job_stop_category_enum')
    # ### end Alembic commands ###
