"""harden_agent_guardrails_runtime_dashboard

Revision ID: aad0f4a3b3bc
Revises: e2a947f81c33
Create Date: 2026-06-01 10:51:19.148862

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aad0f4a3b3bc'
down_revision: str | None = 'e2a947f81c33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    sa.Enum(
        'none', 'user_requested', 'cascade_parent_terminated', 'policy_blocked',
        name='agent_termination_category_enum'
    ).create(bind, checkfirst=True)
    sa.Enum('strict_block', 'warn_only', name='agent_recursion_validation_mode_enum').create(bind, checkfirst=True)
    sa.Enum('pass', 'fail', name='agent_last_recursion_validation_status_enum').create(bind, checkfirst=True)
    sa.Enum('functional', 'guardrail', 'posture', 'termination', 'validation', name='execution_event_category_enum').create(bind, checkfirst=True)
    sa.Enum('system', 'user', 'operator', name='execution_actor_type_enum').create(bind, checkfirst=True)

    op.create_table('termination_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('target_agent_job_id', sa.UUID(), nullable=False),
    sa.Column('termination_scope', sa.Enum('node_only', 'cascade_subtree', name='termination_scope_enum'), nullable=False),
    sa.Column('permission_evaluation_outcome', sa.Enum('allowed', 'denied', name='termination_permission_evaluation_outcome_enum'), nullable=False),
    sa.Column('permission_evaluation_reason', sa.String(length=1000), nullable=True),
    sa.Column('request_status', sa.Enum('accepted', 'rejected', 'completed', 'partially_completed', 'failed', name='termination_request_status_enum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_termination_requests_requested_by', 'termination_requests', ['requested_by_user_id'], unique=False)
    op.create_index('ix_termination_requests_target_agent_job', 'termination_requests', ['target_agent_job_id'], unique=False)
    op.create_table('model_guardrail_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=500), nullable=False),
    sa.Column('enforcement_posture', sa.Enum('terminate', 'observe_only', name='model_guardrail_enforcement_posture_enum'), nullable=False),
    sa.Column('usage_limit_hour', sa.Integer(), nullable=True),
    sa.Column('usage_limit_day', sa.Integer(), nullable=True),
    sa.Column('usage_limit_week', sa.Integer(), nullable=True),
    sa.Column('usage_limit_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termination_cascade_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('termination_request_id', sa.UUID(), nullable=False),
    sa.Column('affected_agent_job_id', sa.UUID(), nullable=False),
    sa.Column('cascade_level', sa.Integer(), nullable=False),
    sa.Column('termination_outcome', sa.Enum('terminated', 'already_completed', 'not_found', 'permission_denied', 'failed', name='termination_outcome_enum'), nullable=False),
    sa.Column('outcome_reason', sa.String(length=1000), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affected_agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['termination_request_id'], ['termination_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_termination_cascade_outcomes_agent_job', 'termination_cascade_outcomes', ['affected_agent_job_id'], unique=False)
    op.create_index('ix_termination_cascade_outcomes_request', 'termination_cascade_outcomes', ['termination_request_id'], unique=False)
    op.create_table('agent_run_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_agent_job_id', sa.UUID(), nullable=False),
    sa.Column('child_agent_job_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('delegation', name='agent_run_relationship_type_enum'), nullable=False),
    sa.Column('delegated_via_sop_step_id', sa.UUID(), nullable=True),
    sa.Column('depth_from_root', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegated_via_sop_step_id'], ['sop_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_agent_job_id', 'child_agent_job_id', 'relationship_type', name='uq_agent_run_relationship_edge')
    )
    op.create_index('ix_agent_run_relationships_child', 'agent_run_relationships', ['child_agent_job_id'], unique=False)
    op.create_index('ix_agent_run_relationships_parent', 'agent_run_relationships', ['parent_agent_job_id'], unique=False)
    op.create_table('model_guardrail_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_guardrail_configuration_id', sa.UUID(), nullable=False),
    sa.Column('agent_job_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('evaluated_period', sa.Enum('hour', 'day', 'week', 'month', name='model_guardrail_evaluated_period_enum'), nullable=False),
    sa.Column('policy_mode', sa.Enum('terminate', 'observe_only', name='model_guardrail_policy_mode_enum'), nullable=False),
    sa.Column('evaluation_outcome', sa.Enum('pass', 'threshold_reached', 'blocked', name='model_guardrail_evaluation_outcome_enum'), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('observed_value', sa.Integer(), nullable=False),
    sa.Column('posture_state', sa.Enum('within_limit', 'approaching_limit', 'breached', name='model_guardrail_posture_state_enum'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_guardrail_configuration_id'], ['model_guardrail_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_guardrail_evaluations_agent_job', 'model_guardrail_evaluations', ['agent_job_id'], unique=False)
    op.create_index('ix_model_guardrail_evaluations_configuration', 'model_guardrail_evaluations', ['model_guardrail_configuration_id'], unique=False)
    op.create_table('model_usage_postures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_guardrail_configuration_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('posture_period', sa.Enum('hour', 'day', 'week', 'month', name='model_usage_posture_period_enum'), nullable=False),
    sa.Column('usage_value', sa.Integer(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('posture_state', sa.Enum('within_limit', 'approaching_limit', 'breached', name='model_usage_posture_state_enum'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['model_guardrail_configuration_id'], ['model_guardrail_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_guardrail_configuration_id', 'posture_period', name='uq_model_usage_posture_configuration_period')
    )
    op.create_index('ix_model_usage_postures_model', 'model_usage_postures', ['model_id'], unique=False)
    op.create_table('sop_recursion_validation_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checked_agent_type_id', sa.UUID(), nullable=False),
    sa.Column('check_context', sa.Enum('create', 'update', 'run', name='sop_recursion_check_context_enum'), nullable=False),
    sa.Column('check_outcome', sa.Enum('pass', 'fail', name='sop_recursion_check_outcome_enum'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['checked_agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['identities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sop_recursion_validation_checks_agent_type', 'sop_recursion_validation_checks', ['checked_agent_type_id'], unique=False)
    op.create_table('guardrail_threshold_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_guardrail_evaluation_id', sa.UUID(), nullable=False),
    sa.Column('agent_job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('observe_only_threshold_reached', name='guardrail_threshold_event_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='guardrail_threshold_severity_enum'), nullable=False),
    sa.Column('display_message', sa.String(length=1000), nullable=False),
    sa.Column('emitted_to_execution_log', sa.Boolean(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_guardrail_evaluation_id'], ['model_guardrail_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guardrail_threshold_events_agent_job', 'guardrail_threshold_events', ['agent_job_id'], unique=False)
    op.create_table('sop_recursion_validation_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_check_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.Enum('cycle_detected', 'dead_loop_risk', 'max_depth_violation', 'repeated_delegation_path', name='sop_recursion_finding_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'error', name='sop_recursion_finding_severity_enum'), nullable=False),
    sa.Column('involved_sop_id', sa.UUID(), nullable=True),
    sa.Column('involved_sop_step_id', sa.UUID(), nullable=True),
    sa.Column('path_signature', sa.String(length=2000), nullable=True),
    sa.Column('recommendation', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['involved_sop_id'], ['sops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['involved_sop_step_id'], ['sop_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_check_id'], ['sop_recursion_validation_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sop_recursion_validation_findings_check', 'sop_recursion_validation_findings', ['validation_check_id'], unique=False)
    op.add_column('agent_jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.add_column('agent_jobs', sa.Column('root_job_id', sa.UUID(), nullable=True))
    op.add_column('agent_jobs', sa.Column('delegation_depth', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_jobs', sa.Column('model_guardrail_configuration_id', sa.UUID(), nullable=True))
    op.add_column('agent_jobs', sa.Column('terminated_by_request_id', sa.UUID(), nullable=True))
    op.add_column('agent_jobs', sa.Column('termination_category', sa.Enum('none', 'user_requested', 'cascade_parent_terminated', 'policy_blocked', name='agent_termination_category_enum'), server_default='none', nullable=False))
    op.create_foreign_key(None, 'agent_jobs', 'termination_requests', ['terminated_by_request_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_jobs', 'agent_jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_jobs', 'agent_jobs', ['root_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_jobs', 'model_guardrail_configurations', ['model_guardrail_configuration_id'], ['id'], ondelete='SET NULL')
    op.add_column('agent_types', sa.Column('recursion_validation_mode', sa.Enum('strict_block', 'warn_only', name='agent_recursion_validation_mode_enum'), server_default='strict_block', nullable=False))
    op.add_column('agent_types', sa.Column('last_recursion_validation_status', sa.Enum('pass', 'fail', name='agent_last_recursion_validation_status_enum'), nullable=True))
    op.add_column('agent_types', sa.Column('last_recursion_validation_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('execution_log_entries', sa.Column('event_category', sa.Enum('functional', 'guardrail', 'posture', 'termination', 'validation', name='execution_event_category_enum'), server_default='functional', nullable=False))
    op.add_column('execution_log_entries', sa.Column('correlation_id', sa.String(length=200), nullable=True))
    op.add_column('execution_log_entries', sa.Column('actor_type', sa.Enum('system', 'user', 'operator', name='execution_actor_type_enum'), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_log_entries', 'actor_type')
    op.drop_column('execution_log_entries', 'correlation_id')
    op.drop_column('execution_log_entries', 'event_category')
    op.drop_column('agent_types', 'last_recursion_validation_at')
    op.drop_column('agent_types', 'last_recursion_validation_status')
    op.drop_column('agent_types', 'recursion_validation_mode')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_column('agent_jobs', 'termination_category')
    op.drop_column('agent_jobs', 'terminated_by_request_id')
    op.drop_column('agent_jobs', 'model_guardrail_configuration_id')
    op.drop_column('agent_jobs', 'delegation_depth')
    op.drop_column('agent_jobs', 'root_job_id')
    op.drop_column('agent_jobs', 'parent_job_id')
    op.drop_index('ix_sop_recursion_validation_findings_check', table_name='sop_recursion_validation_findings')
    op.drop_table('sop_recursion_validation_findings')
    op.drop_index('ix_guardrail_threshold_events_agent_job', table_name='guardrail_threshold_events')
    op.drop_table('guardrail_threshold_events')
    op.drop_index('ix_sop_recursion_validation_checks_agent_type', table_name='sop_recursion_validation_checks')
    op.drop_table('sop_recursion_validation_checks')
    op.drop_index('ix_model_usage_postures_model', table_name='model_usage_postures')
    op.drop_table('model_usage_postures')
    op.drop_index('ix_model_guardrail_evaluations_configuration', table_name='model_guardrail_evaluations')
    op.drop_index('ix_model_guardrail_evaluations_agent_job', table_name='model_guardrail_evaluations')
    op.drop_table('model_guardrail_evaluations')
    op.drop_index('ix_agent_run_relationships_parent', table_name='agent_run_relationships')
    op.drop_index('ix_agent_run_relationships_child', table_name='agent_run_relationships')
    op.drop_table('agent_run_relationships')
    op.drop_index('ix_termination_cascade_outcomes_request', table_name='termination_cascade_outcomes')
    op.drop_index('ix_termination_cascade_outcomes_agent_job', table_name='termination_cascade_outcomes')
    op.drop_table('termination_cascade_outcomes')
    op.drop_table('model_guardrail_configurations')
    op.drop_index('ix_termination_requests_target_agent_job', table_name='termination_requests')
    op.drop_index('ix_termination_requests_requested_by', table_name='termination_requests')
    op.drop_table('termination_requests')
    # ### end Alembic commands ###
