"""provider-level-model-management

Revision ID: afaffd73dcb8
Revises: 232324b61ea4
Create Date: 2026-05-06 09:05:39.893734

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afaffd73dcb8'
down_revision: str | None = '232324b61ea4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: uq_agent_role_skill and uq_agent_role_sop already exist in DB (pre-existing)
    # op.create_unique_constraint('uq_agent_role_skill', 'agent_role_skills', ['role_id', 'skill_id'])
    # op.create_unique_constraint('uq_agent_role_sop', 'agent_role_sops', ['role_id', 'sop_id'])
    op.add_column('agent_types', sa.Column('model_id', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('agent_types_model_config_id_fkey'), 'agent_types', type_='foreignkey')
    op.drop_column('agent_types', 'model_name')
    op.drop_column('agent_types', 'model_config_id')
    op.add_column('model_configs', sa.Column('enabled_models', postgresql.JSON(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'enabled_models')
    op.add_column('agent_types', sa.Column('model_config_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agent_types', sa.Column('model_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_types_model_config_id_fkey'), 'agent_types', 'model_configs', ['model_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agent_types', 'model_id')
    # Note: uq_agent_role_sop and uq_agent_role_skill are NOT dropped (they pre-existed)
    # ### end Alembic commands ###
