"""replace_primary_sop_with_multi_sop_skill_bindings

Revision ID: b38732c813c9
Revises: a1b2c3d4e5f7
Create Date: 2026-06-03 20:11:10.147288

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b38732c813c9'
down_revision: str | None = 'a1b2c3d4e5f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_type_skill_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type_id', 'skill_id', name='uq_agent_type_skill_binding')
    )
    op.create_table('agent_type_sop_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type_id', 'sop_id', name='uq_agent_type_sop_binding')
    )

    # Data migration: migrate existing primary_sop_id values into binding rows
    op.execute("""
        INSERT INTO agent_type_sop_bindings (id, agent_type_id, sop_id, "order", created_at)
        SELECT gen_random_uuid(), id, primary_sop_id, 0, NOW()
        FROM agent_types
        WHERE primary_sop_id IS NOT NULL
    """)

    op.drop_constraint(op.f('agent_types_primary_sop_id_fkey'), 'agent_types', type_='foreignkey')
    op.drop_column('agent_types', 'primary_sop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_types', sa.Column('primary_sop_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_types_primary_sop_id_fkey'), 'agent_types', 'sops', ['primary_sop_id'], ['id'], ondelete='SET NULL')
    op.drop_table('agent_type_sop_bindings')
    op.drop_table('agent_type_skill_bindings')
    # ### end Alembic commands ###
