"""add_oauth_expiry_to_mcp_sessions

Revision ID: d34d6078aae3
Revises: f8a9b2c3d4e5
Create Date: 2026-05-05 20:44:28.743963

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd34d6078aae3'
down_revision: str | None = 'f8a9b2c3d4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_unique_constraint_if_missing(
    table_name: str,
    constraint_name: str,
    columns: list[str],
) -> None:
    """Create a unique constraint only when it does not already exist."""
    bind = op.get_bind()
    exists = bind.execute(
        sa.text(
            """
            SELECT 1
            FROM pg_constraint
            WHERE conname = :constraint_name
            UNION ALL
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = :constraint_name
              AND n.nspname = current_schema()
            LIMIT 1
            """
        ),
        {"constraint_name": constraint_name},
    ).scalar()
    if not exists:
        op.create_unique_constraint(constraint_name, table_name, columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_unique_constraint_if_missing('agent_role_skills', 'uq_agent_role_skill', ['role_id', 'skill_id'])
    _create_unique_constraint_if_missing('agent_role_sops', 'uq_agent_role_sop', ['role_id', 'sop_id'])
    op.add_column('mcp_sessions', sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_sessions', 'oauth_metadata')
    op.drop_column('mcp_sessions', 'oauth_refresh_expires_at')
    op.drop_column('mcp_sessions', 'oauth_expires_at')
    op.drop_constraint('uq_agent_role_sop', 'agent_role_sops', type_='unique')
    op.drop_constraint('uq_agent_role_skill', 'agent_role_skills', type_='unique')
    # ### end Alembic commands ###
