"""add_oauth_expiry_to_mcp_sessions

Revision ID: d34d6078aae3
Revises: f8a9b2c3d4e5
Create Date: 2026-05-05 20:44:28.743963

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd34d6078aae3'
down_revision: str | None = 'f8a9b2c3d4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agent_role_skill', 'agent_role_skills', ['role_id', 'skill_id'])
    op.create_unique_constraint('uq_agent_role_sop', 'agent_role_sops', ['role_id', 'sop_id'])
    op.add_column('mcp_sessions', sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mcp_sessions', sa.Column('oauth_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_sessions', 'oauth_metadata')
    op.drop_column('mcp_sessions', 'oauth_refresh_expires_at')
    op.drop_column('mcp_sessions', 'oauth_expires_at')
    op.drop_constraint('uq_agent_role_sop', 'agent_role_sops', type_='unique')
    op.drop_constraint('uq_agent_role_skill', 'agent_role_skills', type_='unique')
    # ### end Alembic commands ###
