"""add agent_role_mcp_sessions table

Revision ID: d4abc4c3a961
Revises: 7a9f2e3b4c5d
Create Date: 2026-05-08 14:00:16.562395

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd4abc4c3a961'
down_revision: str | None = '7a9f2e3b4c5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_role_mcp_sessions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('mcp_session_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mcp_session_id'], ['mcp_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['agent_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'mcp_session_id'),
    sa.UniqueConstraint('role_id', 'server_id', name='uq_agent_role_mcp_session_server')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_role_mcp_sessions')
    # ### end Alembic commands ###
