"""make_access_request_group_id_optional

Revision ID: dd1dd4f940eb
Revises: 52908f217517
Create Date: 2026-04-29 23:09:25.812145

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dd1dd4f940eb'
down_revision: str | None = '52908f217517'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_requests', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_user_group_status_pending'), 'access_requests', type_='unique')
    op.drop_constraint(op.f('access_requests_group_id_fkey'), 'access_requests', type_='foreignkey')
    op.create_foreign_key(None, 'access_requests', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.create_foreign_key(op.f('access_requests_group_id_fkey'), 'access_requests', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_group_status_pending'), 'access_requests', ['user_id', 'group_id', 'status'], postgresql_nulls_not_distinct=False)
    op.alter_column('access_requests', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
