"""agent-runtime-with-gateway

Revision ID: df2225d787c5
Revises: dd1dd4f940eb
Create Date: 2026-05-01 23:38:55.500762

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2225d787c5'
down_revision: str | None = 'dd1dd4f940eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('identity_type', sa.Enum('oauth', 'service_account', 'user_delegate', name='agent_identity_type_enum'), nullable=False),
    sa.Column('client_id', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deprovisioned', name='agent_identity_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_role_skills',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['agent_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id'),
    sa.UniqueConstraint('role_id', 'skill_id', name='uq_agent_role_skill')
    )
    op.create_table('agent_role_sops',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('sop_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['agent_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'sop_id'),
    sa.UniqueConstraint('role_id', 'sop_id', name='uq_agent_role_sop')
    )
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='agent_job_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['identities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agent_skill_assignments')
    # Create new enum types before adding columns that use them
    op.execute("CREATE TYPE agent_input_type_enum AS ENUM ('none', 'typed', 'conversation')")
    op.execute("CREATE TYPE agent_output_type_enum AS ENUM ('auto', 'typed', 'markdown')")
    op.add_column('agent_types', sa.Column('identity_id', sa.UUID(), nullable=True))
    op.add_column('agent_types', sa.Column('role_id', sa.UUID(), nullable=True))
    op.add_column('agent_types', sa.Column('system_instruction', sa.Text(), nullable=True))
    op.add_column('agent_types', sa.Column('input_type', sa.Enum('none', 'typed', 'conversation', name='agent_input_type_enum'), nullable=False, server_default='none'))
    op.add_column('agent_types', sa.Column('input_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_types', sa.Column('output_type', sa.Enum('auto', 'typed', 'markdown', name='agent_output_type_enum'), nullable=False, server_default='auto'))
    op.add_column('agent_types', sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('agent_types_sop_id_fkey'), 'agent_types', type_='foreignkey')
    op.create_foreign_key(None, 'agent_types', 'agent_identities', ['identity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_types', 'agent_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agent_types', 'identity_subject')
    op.drop_column('agent_types', 'system_prompt')
    op.drop_column('agent_types', 'max_instances')
    op.drop_column('agent_types', 'sop_id')
    op.drop_column('agent_types', 'mode')
    # Drop the now-unused agent_mode_enum type
    op.execute("DROP TYPE IF EXISTS agent_mode_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE agent_mode_enum AS ENUM ('sop-agent', 'skillful-agent')")
    op.add_column('agent_types', sa.Column('mode', postgresql.ENUM('sop-agent', 'skillful-agent', name='agent_mode_enum'), autoincrement=False, nullable=False))
    op.add_column('agent_types', sa.Column('sop_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agent_types', sa.Column('max_instances', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('agent_types', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_types', sa.Column('identity_subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_types', type_='foreignkey')
    op.drop_constraint(None, 'agent_types', type_='foreignkey')
    op.create_foreign_key(op.f('agent_types_sop_id_fkey'), 'agent_types', 'sops', ['sop_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agent_types', 'output_schema')
    op.drop_column('agent_types', 'output_type')
    op.drop_column('agent_types', 'input_schema')
    op.drop_column('agent_types', 'input_type')
    op.drop_column('agent_types', 'system_instruction')
    op.drop_column('agent_types', 'role_id')
    op.drop_column('agent_types', 'identity_id')
    op.create_table('agent_skill_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], name=op.f('agent_skill_assignments_agent_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('agent_skill_assignments_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_skill_assignments_pkey')),
    sa.UniqueConstraint('agent_type_id', 'skill_id', name=op.f('uq_agent_skill_assignment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('agent_jobs')
    op.drop_table('agent_role_sops')
    op.drop_table('agent_role_skills')
    op.drop_table('agent_roles')
    op.drop_table('agent_identities')
    # Drop enum types added in upgrade
    op.execute("DROP TYPE IF EXISTS agent_input_type_enum")
    op.execute("DROP TYPE IF EXISTS agent_output_type_enum")
    # ### end Alembic commands ###
