"""add_agent_plans

Revision ID: fcbe5b250e08
Revises: d4abc4c3a961
Create Date: 2026-05-09 19:51:38.661588

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbe5b250e08'
down_revision: str | None = 'd4abc4c3a961'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('plan_steps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('topology', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_status', sa.Enum('pending', 'success', 'failed', name='agent_plan_status_enum'), nullable=False),
    sa.Column('generation_error', sa.String(length=1000), nullable=True),
    sa.Column('agent_config_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type_id', name='uq_agent_plans_agent_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_plans')
    # ### end Alembic commands ###
