"""Pydantic schemas for Certificate Authority API."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


# ── Request schemas ───────────────────────────────────────────────────────────


class BootstrapRequest(BaseModel):
    """Request body for POST /internal/bootstrap."""

    service_name: str = Field(
        ...,
        description="Logical service name, e.g. 'agent-runtime' or 'communication-hub'",
    )
    service_type: Literal["agent_instance", "service", "test_service"] = Field(
        ...,
        description="Certificate type: 'agent_instance' (24h), 'service' (30d), or 'test_service' (30d, test suite only)",
    )
    public_key: str = Field(..., description="PEM-encoded RSA public key generated by the caller")


class CertificateIssueRequest(BaseModel):
    """Request body for POST /certificates/issue."""

    agent_type_id: uuid.UUID = Field(..., description="UUID of the agent type to issue cert for")
    instance_id: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Unique instance identifier (e.g. hostname or job ID)",
    )


class CertificateRevokeRequest(BaseModel):
    """Request body for POST /certificates/revoke."""

    serial_number: str = Field(..., description="Certificate serial number to revoke")
    reason: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Human-readable reason for revocation",
    )


class CertificateValidateRequest(BaseModel):
    """Request body for POST /internal/certificates/validate."""

    certificate_pem: str = Field(..., description="PEM-encoded certificate to validate")
    requested_operation: str | None = Field(
        None, description="Operation being authorized (for audit log)"
    )


class AuthorizeToolCallRequest(BaseModel):
    """Request body for POST /internal/authorize/tool-call."""

    certificate_serial_number: str = Field(..., description="Agent certificate serial number")
    tool_name: str = Field(..., description="Fully-qualified tool identifier")
    tool_params: dict | None = Field(None, description="Tool parameters (for audit logging)")


# ── Response schemas ──────────────────────────────────────────────────────────


class CACertificateResponse(BaseModel):
    """Response for GET /certificates/ca."""

    certificate_pem: str
    expires_at: datetime
    serial_number: str


class CertificateIssueResponse(BaseModel):
    """Response for POST /certificates/issue."""

    certificate_pem: str
    private_key_pem: str
    serial_number: str
    expires_at: datetime


class CertificateRevokeResponse(BaseModel):
    """Response for POST /certificates/revoke."""

    revoked_at: datetime
    serial_number: str


class CertificateValidateResponse(BaseModel):
    """Response for POST /internal/certificates/validate — success case."""

    valid: bool
    agent_type_id: uuid.UUID | None = None
    instance_id: str | None = None
    serial_number: str | None = None
    expires_at: datetime | None = None
    reason: str | None = None  # Only set when valid=False


class AuthorizeToolCallResponse(BaseModel):
    """Response for POST /internal/authorize/tool-call."""

    authorized: bool
    identity_token: str | None = None
    identity_id: uuid.UUID | None = None
    agent_type_id: uuid.UUID | None = None
    reason: str | None = None
    required_permission: str | None = None
    agent_type: str | None = None


class BootstrapResponse(BaseModel):
    """Response for POST /internal/bootstrap."""

    certificate_pem: str = Field(..., description="CA-signed PEM certificate for the service")
    ca_certificate_pem: str = Field(..., description="CA public certificate PEM for validation")
    serial_number: str
    expires_at: datetime
