apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parthenon.configMapName" . }}
  labels:
    {{- include "parthenon.labels" . | nindent 4 }}
data:
  OIDC_PROVIDER_URL: {{ .Values.configMap.oidcProviderUrl | quote }}
  JWT_AUDIENCE: {{ .Values.configMap.jwtAudience | quote }}
  VITE_API_BASE_URL: {{ .Values.configMap.viteApiBaseUrl | quote }}
  VITE_WS_BASE_URL: {{ .Values.configMap.viteWsBaseUrl | quote }}
  VITE_OIDC_AUTHORITY: {{ .Values.configMap.viteOidcAuthority | quote }}
  VITE_OIDC_CLIENT_ID: {{ .Values.configMap.viteOidcClientId | quote }}

---
{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "parthenon.fullname" . }}-otel-config
  labels:
    {{- include "parthenon.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    {{- .Values.otelCollector.config | nindent 4 }}
{{- end }}
